# This is the default configuration when no flavor is specified
dev:
    storage: local
    storage_path: /registry
    loglevel: debug
    standalone: true # do not use public index
    secret_key: test-registry

